name: Deploy Vite React App to S3

on:
  push:
    branches:
      - master # Change this if you're using a different branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (ensure compatibility with the version you are using)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.0' # Ensure compatibility with your project

      # Debug: Check Node.js version
      - name: Check Node.js version
        run: node -v

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Debug: Run a simple check on dependencies
      - name: Verify dependencies
        run: npm ls

      # Build the application
      - name: Build Vite app
        run: npm run build

      # Deploy to S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: dist # Vite outputs the build to the 'dist' folder by default
